### ISSUE TITLE
inv -l : ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by FlowDrucka64** [faasm/cpp#98]
After pulling the recent changes into my fork the following happens when trying to execute ``inv -l`` within the cpp container:
```
flowd@DESKTOP-QF2HQEJ:~/faasm$ ./bin/cli.sh cpp
[+] Running 1/0
 ⠿ Container faasm-dev-cpp-1  Running                                                                              0.0s

----------------------------------
CPP CLI
Version: 0.1.7
Project root: /code/cpp
Mode: container
----------------------------------

(cpp) root@e8c3750591dd:/code/cpp# inv -l
Traceback (most recent call last):
  File "/code/cpp/venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/code/cpp/venv/lib/python3.8/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/code/cpp/venv/lib/python3.8/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/code/cpp/venv/lib/python3.8/site-packages/invoke/program.py", line 699, in load_collection
    module, parent = loader.load(coll_name)
  File "/code/cpp/venv/lib/python3.8/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/cpp/tasks/__init__.py", line 6, in <module>
    from . import func
  File "/code/cpp/tasks/func.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Since the tests seem to run through just fine I'm wondering if this error is on my end?
(I removed the docker container and image completely with all of its layers and repulled all of it just to make sure but that did not fix it)

**Comment by FlowDrucka64** [comment]
I fixed it by installing the requirements by myself: ``pip3 install -r requirements.txt``
Though I feel like this shouldn't be necessary since this should already happen [here](https://github.com/faasm/cpp/blob/956f84cd7bf60d2cda422af21db123ea71182627/docker/cpp-sysroot.dockerfile#L32).
